version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
     - .env
    image: automonyet:latest
    restart: unless-stopped
    networks:
      - monyet_default
      
networks:
  monyet_default:
    external: true